// export const DISCOUNT_ADD_ITEM = "DISCOUNT_ADD_ITEM";
// export const DISCOUNT_VERIFY_ITEM = "DISCOUNT_VERIFY_ITEM";
// export const DISCOUNT_GETALL_ITEM = "DISCOUNT_GETALL_ITEM";

export const DISCOUNT_LIST_SUCCESS = "DISCOUNT_LIST_SUCCESS";
export const DISCOUNT_LIST_FAIL = "DISCOUNT_LIST_FAIL";

export const DISCOUNT_EDIT_SUCCESS = "DISCOUNT_EDIT_SUCCESS";
export const DISCOUNT_EDIT_FAIL = "DISCOUNT_EDIT_FAIL";
