export const ORDER_GETALL_SUCCESS = "ORDER_GETALL_ITEM";

export const ORDER_GETALL_FAIL = "ORDER_GETALL_FAIL";

export const ORDER_DETAIL_SUCCESS = "ORDER_GETALL_ITEM";

export const ORDER_DETAIL_FAIL = "ORDER_GETALL_FAIL";
